import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NavBar from "@/ui/NavBar/navbar"
import "bootstrap/dist/css/bootstrap.min.css"
const poppins = Poppins({subsets:["latin"], weight: ['700', '400']})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
          <NavBar/>
          {children}
        </body>
    </html>
  );
}

